export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SET_TOKEN = 'SET_TOKEN';
export const FETCH_USER_DATA_START = 'FETCH_USER_DATA_START';
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAILURE = 'FETCH_USER_DATA_FAILURE';



export const SET_USER_DATA = 'SET_USER_DATA';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
export const SET_USER_ERROR = 'SET_USER_ERROR';
export const USER_UPDATED = 'USER_UPDATED';
export const SET_COMMENTS = 'SET_COMMENTS';