export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const APPROVE_DEPOSIT = "APPROVE_DEPOSIT";
export const REJECT_DEPOSIT = "REJECT_DEPOSIT";
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const FETCH_PENDING_DEPOSITS = 'FETCH_PENDING_DEPOSITS';
export const FETCH_PENDING_DEPOSITS_SUCCESS = "FETCH_PENDING_DEPOSITS_SUCCESS";
export const FETCH_PENDING_DEPOSITS_FAIL= "FETCH_PENDING_DEPOSITS_FAIL";